export const featureConfigs = [
  {
    key: 'permit-closeout-readiness',
    path: '/permit-closeout-readiness',
    title: 'Permit Closeout Readiness',
    icon: '📑',
    apiPath: '/api/permit-closeout-readiness',
    tableColumns: [
      { key: 'permit_number', label: 'Permit' },
      { key: 'site_name', label: 'Site' },
      { key: 'inspector_name', label: 'Inspector' },
      { key: 'closeout_stage', label: 'Stage' },
      { key: 'readiness_score', label: 'Readiness', type: 'progress' },
      { key: 'blocking_items', label: 'Blocks' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'permit_number', label: 'Permit Number' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'inspector_name', label: 'Inspector' },
      { key: 'closeout_stage', label: 'Closeout Stage' },
      { key: 'readiness_score', label: 'Readiness Score', type: 'progress' },
      { key: 'blocking_items', label: 'Blocking Items' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'next_action', label: 'Next Action', fullWidth: true }
    ],
    formFields: [
      { key: 'permit_number', label: 'Permit Number', required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'inspector_name', label: 'Inspector', required: true },
      { key: 'closeout_stage', label: 'Closeout Stage', required: true },
      { key: 'readiness_score', label: 'Readiness Score', type: 'number' },
      { key: 'blocking_items', label: 'Blocking Items', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['ready', 'action_required', 'blocked', 'closed'] },
      { key: 'next_action', label: 'Next Action', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'inspections',
    path: '/inspections',
    title: 'Site Inspections',
    icon: '🔍',
    apiPath: '/api/inspections',
    tableColumns: [
      { key: 'site_name', label: 'Site Name' },
      { key: 'inspector_name', label: 'Inspector' },
      { key: 'inspection_date', label: 'Date', type: 'date' },
      { key: 'inspection_type', label: 'Type' },
      { key: 'overall_rating', label: 'Rating', type: 'badge' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'num_workers_onsite', label: 'Workers' }
    ],
    detailFields: [
      { key: 'site_name', label: 'Site Name' },
      { key: 'site_address', label: 'Address' },
      { key: 'inspector_name', label: 'Inspector' },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date' },
      { key: 'inspection_type', label: 'Type' },
      { key: 'overall_rating', label: 'Overall Rating' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'weather_conditions', label: 'Weather' },
      { key: 'num_workers_onsite', label: 'Workers Onsite' },
      { key: 'next_inspection_date', label: 'Next Inspection', type: 'date' },
      { key: 'findings', label: 'Findings', fullWidth: true },
      { key: 'recommendations', label: 'Recommendations', fullWidth: true }
    ],
    formFields: [
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'site_address', label: 'Site Address', required: true },
      { key: 'inspector_name', label: 'Inspector Name', required: true },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date', required: true },
      { key: 'inspection_type', label: 'Type', type: 'select', options: ['Routine', 'Safety Audit', 'Pre-Construction', 'Follow-up', 'Specialty'] },
      { key: 'overall_rating', label: 'Rating', type: 'select', options: ['Excellent', 'Good', 'Satisfactory', 'Needs Improvement', 'Poor'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'action_required'] },
      { key: 'weather_conditions', label: 'Weather' },
      { key: 'num_workers_onsite', label: 'Workers Onsite', type: 'number' },
      { key: 'next_inspection_date', label: 'Next Inspection Date', type: 'date' },
      { key: 'findings', label: 'Findings', type: 'textarea', fullWidth: true },
      { key: 'recommendations', label: 'Recommendations', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'violations',
    path: '/violations',
    title: 'Violations',
    icon: '⚠️',
    apiPath: '/api/violations',
    tableColumns: [
      { key: 'violation_code', label: 'Code' },
      { key: 'title', label: 'Title' },
      { key: 'severity', label: 'Severity', type: 'severity' },
      { key: 'site_name', label: 'Site' },
      { key: 'date_identified', label: 'Date', type: 'date' },
      { key: 'fine_amount', label: 'Fine', type: 'money' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'violation_code', label: 'Violation Code' },
      { key: 'title', label: 'Title' },
      { key: 'severity', label: 'Severity', type: 'severity' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'location_detail', label: 'Location Detail' },
      { key: 'date_identified', label: 'Date Identified', type: 'date' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'fine_amount', label: 'Fine Amount', type: 'money' },
      { key: 'osha_standard', label: 'OSHA Standard' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'corrective_action', label: 'Corrective Action', fullWidth: true }
    ],
    formFields: [
      { key: 'violation_code', label: 'Violation Code', required: true },
      { key: 'title', label: 'Title', required: true },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'major', 'moderate', 'minor'], required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'location_detail', label: 'Location Detail' },
      { key: 'date_identified', label: 'Date Identified', type: 'date', required: true },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'resolved'] },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'fine_amount', label: 'Fine Amount', type: 'number' },
      { key: 'osha_standard', label: 'OSHA Standard' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true, required: true },
      { key: 'corrective_action', label: 'Corrective Action', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'checklists',
    path: '/checklists',
    title: 'Safety Checklists',
    icon: '✅',
    apiPath: '/api/checklists',
    tableColumns: [
      { key: 'checklist_name', label: 'Checklist' },
      { key: 'site_name', label: 'Site' },
      { key: 'category', label: 'Category' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'completion_percentage', label: 'Progress', type: 'progress' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'checklist_name', label: 'Checklist Name' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'category', label: 'Category' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'completion_percentage', label: 'Completion', type: 'progress' },
      { key: 'total_items', label: 'Total Items' },
      { key: 'completed_items', label: 'Completed Items' },
      { key: 'notes', label: 'Notes', fullWidth: true }
    ],
    formFields: [
      { key: 'checklist_name', label: 'Checklist Name', required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Fall Protection', 'Scaffolding', 'Excavation', 'Electrical', 'Fire Safety', 'Heavy Equipment', 'Confined Space', 'PPE', 'General Safety', 'HazMat', 'Equipment', 'Health', 'Emergency', 'Hot Work', 'Traffic Safety'] },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'overdue'] },
      { key: 'total_items', label: 'Total Items', type: 'number', required: true },
      { key: 'completed_items', label: 'Completed Items', type: 'number' },
      { key: 'completion_percentage', label: 'Completion %', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'incidents',
    path: '/incidents',
    title: 'Incident Reports',
    icon: '🚨',
    apiPath: '/api/incidents',
    tableColumns: [
      { key: 'incident_number', label: 'Number' },
      { key: 'title', label: 'Title' },
      { key: 'incident_type', label: 'Type' },
      { key: 'severity', label: 'Severity', type: 'severity' },
      { key: 'site_name', label: 'Site' },
      { key: 'incident_date', label: 'Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'incident_number', label: 'Incident Number' },
      { key: 'title', label: 'Title' },
      { key: 'incident_type', label: 'Type' },
      { key: 'severity', label: 'Severity', type: 'severity' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'location_detail', label: 'Location' },
      { key: 'incident_date', label: 'Incident Date', type: 'date' },
      { key: 'reported_by', label: 'Reported By' },
      { key: 'injuries_count', label: 'Injuries' },
      { key: 'osha_recordable', label: 'OSHA Recordable', type: 'boolean' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'injury_details', label: 'Injury Details', fullWidth: true },
      { key: 'root_cause', label: 'Root Cause', fullWidth: true },
      { key: 'immediate_actions', label: 'Immediate Actions', fullWidth: true },
      { key: 'witnesses', label: 'Witnesses', fullWidth: true }
    ],
    formFields: [
      { key: 'incident_number', label: 'Incident Number', required: true },
      { key: 'title', label: 'Title', required: true },
      { key: 'incident_type', label: 'Type', type: 'select', options: ['Fall', 'Struck-By', 'Caught-In', 'Electrical', 'Chemical', 'Fire', 'Vehicle', 'Health', 'Near Miss', 'Cave-in', 'Structural', 'HazMat', 'Utility'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'major', 'moderate', 'minor'], required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'location_detail', label: 'Location Detail' },
      { key: 'incident_date', label: 'Incident Date', type: 'datetime-local', required: true },
      { key: 'reported_by', label: 'Reported By', required: true },
      { key: 'injuries_count', label: 'Number of Injuries', type: 'number' },
      { key: 'osha_recordable', label: 'OSHA Recordable', type: 'select', options: ['true', 'false'] },
      { key: 'status', label: 'Status', type: 'select', options: ['reported', 'under_investigation', 'resolved'] },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true, required: true },
      { key: 'injury_details', label: 'Injury Details', type: 'textarea', fullWidth: true },
      { key: 'root_cause', label: 'Root Cause', type: 'textarea', fullWidth: true },
      { key: 'immediate_actions', label: 'Immediate Actions', type: 'textarea', fullWidth: true },
      { key: 'witnesses', label: 'Witnesses', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'equipment',
    path: '/equipment',
    title: 'Equipment Inspections',
    icon: '🏗️',
    apiPath: '/api/equipment',
    tableColumns: [
      { key: 'equipment_name', label: 'Equipment' },
      { key: 'equipment_type', label: 'Type' },
      { key: 'equipment_id', label: 'ID' },
      { key: 'site_name', label: 'Site' },
      { key: 'condition', label: 'Condition', type: 'severity' },
      { key: 'inspection_date', label: 'Inspected', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'equipment_name', label: 'Equipment Name' },
      { key: 'equipment_type', label: 'Type' },
      { key: 'equipment_id', label: 'Equipment ID' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'inspector_name', label: 'Inspector' },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date' },
      { key: 'next_inspection_date', label: 'Next Inspection', type: 'date' },
      { key: 'condition', label: 'Condition' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'hours_used', label: 'Hours Used' },
      { key: 'certification_expiry', label: 'Certification Expiry', type: 'date' },
      { key: 'findings', label: 'Findings', fullWidth: true },
      { key: 'maintenance_needed', label: 'Maintenance Needed', fullWidth: true }
    ],
    formFields: [
      { key: 'equipment_name', label: 'Equipment Name', required: true },
      { key: 'equipment_type', label: 'Type', type: 'select', options: ['Tower Crane', 'Excavator', 'Aerial Lift', 'Skid Steer', 'Power Tool', 'Compactor', 'Air Compressor', 'Welder', 'Generator', 'Concrete Pump', 'Survey Equipment'] },
      { key: 'equipment_id', label: 'Equipment ID', required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'inspector_name', label: 'Inspector', required: true },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date', required: true },
      { key: 'next_inspection_date', label: 'Next Inspection', type: 'date' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['Excellent', 'Good', 'Fair', 'Poor'], required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'needs_repair', 'out_of_service'] },
      { key: 'hours_used', label: 'Hours Used', type: 'number' },
      { key: 'certification_expiry', label: 'Certification Expiry', type: 'date' },
      { key: 'findings', label: 'Findings', type: 'textarea', fullWidth: true },
      { key: 'maintenance_needed', label: 'Maintenance Needed', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'certifications',
    path: '/certifications',
    title: 'Worker Certifications',
    icon: '📋',
    apiPath: '/api/certifications',
    tableColumns: [
      { key: 'worker_name', label: 'Worker' },
      { key: 'certification_type', label: 'Certification' },
      { key: 'issuing_authority', label: 'Authority' },
      { key: 'issue_date', label: 'Issued', type: 'date' },
      { key: 'expiry_date', label: 'Expires', type: 'date' },
      { key: 'site_name', label: 'Site' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'worker_name', label: 'Worker Name' },
      { key: 'worker_id', label: 'Worker ID' },
      { key: 'certification_type', label: 'Certification Type' },
      { key: 'certification_number', label: 'Certification Number' },
      { key: 'issuing_authority', label: 'Issuing Authority' },
      { key: 'issue_date', label: 'Issue Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'site_name', label: 'Assigned Site' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'notes', label: 'Notes', fullWidth: true }
    ],
    formFields: [
      { key: 'worker_name', label: 'Worker Name', required: true },
      { key: 'worker_id', label: 'Worker ID', required: true },
      { key: 'certification_type', label: 'Certification Type', required: true },
      { key: 'certification_number', label: 'Certification Number' },
      { key: 'issuing_authority', label: 'Issuing Authority', required: true },
      { key: 'issue_date', label: 'Issue Date', type: 'date', required: true },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date', required: true },
      { key: 'site_name', label: 'Assigned Site' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'suspended'] },
      { key: 'notes', label: 'Notes', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'training',
    path: '/training',
    title: 'Safety Training',
    icon: '🎓',
    apiPath: '/api/training',
    tableColumns: [
      { key: 'training_title', label: 'Training' },
      { key: 'training_type', label: 'Type' },
      { key: 'instructor', label: 'Instructor' },
      { key: 'training_date', label: 'Date', type: 'date' },
      { key: 'duration_hours', label: 'Hours' },
      { key: 'attendees_count', label: 'Attendees' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'training_title', label: 'Training Title' },
      { key: 'training_type', label: 'Type' },
      { key: 'instructor', label: 'Instructor' },
      { key: 'site_name', label: 'Site' },
      { key: 'training_date', label: 'Date', type: 'date' },
      { key: 'duration_hours', label: 'Duration (Hours)' },
      { key: 'attendees_count', label: 'Attendees' },
      { key: 'max_capacity', label: 'Max Capacity' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'certification_awarded', label: 'Certification', type: 'boolean' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'materials_provided', label: 'Materials', fullWidth: true }
    ],
    formFields: [
      { key: 'training_title', label: 'Training Title', required: true },
      { key: 'training_type', label: 'Type', type: 'select', options: ['Safety', 'Regulatory', 'Operational', 'Health', 'Emergency'] },
      { key: 'instructor', label: 'Instructor', required: true },
      { key: 'site_name', label: 'Site Name' },
      { key: 'training_date', label: 'Date', type: 'date', required: true },
      { key: 'duration_hours', label: 'Duration (Hours)', type: 'number', required: true },
      { key: 'attendees_count', label: 'Attendees', type: 'number', required: true },
      { key: 'max_capacity', label: 'Max Capacity', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['scheduled', 'completed', 'cancelled'] },
      { key: 'certification_awarded', label: 'Certification Awarded', type: 'select', options: ['true', 'false'] },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'materials_provided', label: 'Materials Provided', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'hazards',
    path: '/hazards',
    title: 'Hazard Assessments',
    icon: '☢️',
    apiPath: '/api/hazards',
    tableColumns: [
      { key: 'hazard_title', label: 'Hazard' },
      { key: 'hazard_type', label: 'Type' },
      { key: 'site_name', label: 'Site' },
      { key: 'risk_level', label: 'Risk Level', type: 'severity' },
      { key: 'probability', label: 'Probability' },
      { key: 'assessed_by', label: 'Assessed By' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'hazard_title', label: 'Hazard Title' },
      { key: 'hazard_type', label: 'Type' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'location_detail', label: 'Location' },
      { key: 'risk_level', label: 'Risk Level', type: 'severity' },
      { key: 'probability', label: 'Probability' },
      { key: 'impact', label: 'Impact' },
      { key: 'assessed_by', label: 'Assessed By' },
      { key: 'assessment_date', label: 'Assessment Date', type: 'date' },
      { key: 'residual_risk', label: 'Residual Risk' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'review_date', label: 'Review Date', type: 'date' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'control_measures', label: 'Control Measures', fullWidth: true }
    ],
    formFields: [
      { key: 'hazard_title', label: 'Hazard Title', required: true },
      { key: 'hazard_type', label: 'Type', type: 'select', options: ['Fall', 'Electrical', 'Chemical', 'Utility Strike', 'Health', 'Confined Space', 'Environmental', 'Traffic', 'Structural', 'Struck-By', 'Cave-In', 'Biological'] },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'location_detail', label: 'Location Detail' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['extreme', 'high', 'medium', 'low'], required: true },
      { key: 'probability', label: 'Probability', type: 'select', options: ['almost_certain', 'likely', 'possible', 'unlikely', 'rare'], required: true },
      { key: 'impact', label: 'Impact', type: 'select', options: ['catastrophic', 'major', 'moderate', 'minor', 'insignificant'], required: true },
      { key: 'assessed_by', label: 'Assessed By', required: true },
      { key: 'assessment_date', label: 'Assessment Date', type: 'date', required: true },
      { key: 'residual_risk', label: 'Residual Risk', type: 'select', options: ['high', 'medium', 'low'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'mitigated', 'closed'] },
      { key: 'review_date', label: 'Review Date', type: 'date' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true, required: true },
      { key: 'control_measures', label: 'Control Measures', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'documents',
    path: '/documents',
    title: 'Compliance Documents',
    icon: '📄',
    apiPath: '/api/documents',
    tableColumns: [
      { key: 'document_title', label: 'Document' },
      { key: 'document_type', label: 'Type' },
      { key: 'site_name', label: 'Site' },
      { key: 'regulatory_body', label: 'Regulatory Body' },
      { key: 'expiry_date', label: 'Expires', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'document_title', label: 'Document Title' },
      { key: 'document_type', label: 'Type' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'regulatory_body', label: 'Regulatory Body' },
      { key: 'document_number', label: 'Document Number' },
      { key: 'responsible_person', label: 'Responsible Person' },
      { key: 'issue_date', label: 'Issue Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'renewal_required', label: 'Renewal Required', type: 'boolean' },
      { key: 'description', label: 'Description', fullWidth: true }
    ],
    formFields: [
      { key: 'document_title', label: 'Document Title', required: true },
      { key: 'document_type', label: 'Type', type: 'select', options: ['Permit', 'License', 'Certificate', 'Plan', 'Assessment', 'Notification', 'Variance'] },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'regulatory_body', label: 'Regulatory Body', required: true },
      { key: 'document_number', label: 'Document Number' },
      { key: 'responsible_person', label: 'Responsible Person' },
      { key: 'issue_date', label: 'Issue Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'pending', 'revoked'] },
      { key: 'renewal_required', label: 'Renewal Required', type: 'select', options: ['true', 'false'] },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'emergency',
    path: '/emergency',
    title: 'Emergency Plans',
    icon: '🚒',
    apiPath: '/api/emergency',
    tableColumns: [
      { key: 'plan_title', label: 'Plan' },
      { key: 'plan_type', label: 'Type' },
      { key: 'site_name', label: 'Site' },
      { key: 'emergency_coordinator', label: 'Coordinator' },
      { key: 'last_drill_date', label: 'Last Drill', type: 'date' },
      { key: 'next_drill_date', label: 'Next Drill', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'plan_title', label: 'Plan Title' },
      { key: 'plan_type', label: 'Type' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'emergency_coordinator', label: 'Coordinator' },
      { key: 'coordinator_phone', label: 'Phone' },
      { key: 'last_drill_date', label: 'Last Drill', type: 'date' },
      { key: 'next_drill_date', label: 'Next Drill', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'last_updated', label: 'Last Updated', type: 'date' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'evacuation_routes', label: 'Evacuation Routes', fullWidth: true },
      { key: 'assembly_points', label: 'Assembly Points', fullWidth: true },
      { key: 'emergency_contacts', label: 'Emergency Contacts', fullWidth: true }
    ],
    formFields: [
      { key: 'plan_title', label: 'Plan Title', required: true },
      { key: 'plan_type', label: 'Type', type: 'select', options: ['Fire', 'Medical', 'Weather', 'Equipment', 'HazMat', 'Rescue', 'Natural Disaster', 'Security', 'Health', 'Traffic', 'Structural', 'Electrical', 'Utility'] },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'emergency_coordinator', label: 'Coordinator', required: true },
      { key: 'coordinator_phone', label: 'Coordinator Phone' },
      { key: 'last_drill_date', label: 'Last Drill Date', type: 'date' },
      { key: 'next_drill_date', label: 'Next Drill Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'needs_update', 'draft', 'expired'] },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { key: 'evacuation_routes', label: 'Evacuation Routes', type: 'textarea', fullWidth: true },
      { key: 'assembly_points', label: 'Assembly Points', type: 'textarea', fullWidth: true },
      { key: 'emergency_contacts', label: 'Emergency Contacts', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'ppe',
    path: '/ppe',
    title: 'PPE Inventory',
    icon: '🦺',
    apiPath: '/api/ppe',
    tableColumns: [
      { key: 'item_name', label: 'Item' },
      { key: 'category', label: 'Category' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'site_name', label: 'Site' },
      { key: 'quantity_in_stock', label: 'Qty', type: 'number' },
      { key: 'unit_cost', label: 'Cost', type: 'money' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'item_name', label: 'Item Name' },
      { key: 'category', label: 'Category' },
      { key: 'ppe_type', label: 'PPE Type' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'model', label: 'Model' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'quantity_in_stock', label: 'In Stock' },
      { key: 'minimum_stock', label: 'Minimum Stock' },
      { key: 'unit_cost', label: 'Unit Cost', type: 'money' },
      { key: 'condition', label: 'Condition' },
      { key: 'last_inspection_date', label: 'Last Inspected', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'storage_location', label: 'Storage Location' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    formFields: [
      { key: 'item_name', label: 'Item Name', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Head Protection', 'Eye Protection', 'Fall Protection', 'Respiratory', 'Foot Protection', 'Visibility', 'Face Protection', 'Hand Protection', 'Hearing Protection', 'Body Protection'] },
      { key: 'ppe_type', label: 'PPE Type', required: true },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'model', label: 'Model' },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'quantity_in_stock', label: 'Quantity', type: 'number', required: true },
      { key: 'minimum_stock', label: 'Minimum Stock', type: 'number', required: true },
      { key: 'unit_cost', label: 'Unit Cost', type: 'number' },
      { key: 'condition', label: 'Condition', type: 'select', options: ['good', 'fair', 'poor'] },
      { key: 'last_inspection_date', label: 'Last Inspected', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'storage_location', label: 'Storage Location' },
      { key: 'status', label: 'Status', type: 'select', options: ['in_stock', 'low_stock', 'out_of_stock', 'ordered'] }
    ]
  },
  {
    key: 'corrections',
    path: '/corrections',
    title: 'Corrective Actions',
    icon: '🔧',
    apiPath: '/api/corrections',
    tableColumns: [
      { key: 'action_title', label: 'Action' },
      { key: 'site_name', label: 'Site' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'action_title', label: 'Action Title' },
      { key: 'related_violation', label: 'Related Violation' },
      { key: 'related_incident', label: 'Related Incident' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'priority', label: 'Priority', type: 'severity' },
      { key: 'due_date', label: 'Due Date', type: 'date' },
      { key: 'completion_date', label: 'Completion Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'verified_by', label: 'Verified By' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'root_cause', label: 'Root Cause', fullWidth: true },
      { key: 'corrective_steps', label: 'Corrective Steps', fullWidth: true },
      { key: 'preventive_measures', label: 'Preventive Measures', fullWidth: true },
      { key: 'verification_method', label: 'Verification Method', fullWidth: true }
    ],
    formFields: [
      { key: 'action_title', label: 'Action Title', required: true },
      { key: 'related_violation', label: 'Related Violation' },
      { key: 'related_incident', label: 'Related Incident' },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'assigned_to', label: 'Assigned To', required: true },
      { key: 'priority', label: 'Priority', type: 'select', options: ['critical', 'high', 'medium', 'low'], required: true },
      { key: 'due_date', label: 'Due Date', type: 'date', required: true },
      { key: 'completion_date', label: 'Completion Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'completed', 'verified'] },
      { key: 'verified_by', label: 'Verified By' },
      { key: 'description', label: 'Description', type: 'textarea', fullWidth: true, required: true },
      { key: 'root_cause', label: 'Root Cause', type: 'textarea', fullWidth: true },
      { key: 'corrective_steps', label: 'Corrective Steps', type: 'textarea', fullWidth: true },
      { key: 'preventive_measures', label: 'Preventive Measures', type: 'textarea', fullWidth: true },
      { key: 'verification_method', label: 'Verification Method', type: 'textarea', fullWidth: true }
    ]
  },
  {
    key: 'reports',
    path: '/reports',
    title: 'Daily Reports',
    icon: '📊',
    apiPath: '/api/reports',
    tableColumns: [
      { key: 'report_date', label: 'Date', type: 'date' },
      { key: 'site_name', label: 'Site' },
      { key: 'submitted_by', label: 'Submitted By' },
      { key: 'weather', label: 'Weather' },
      { key: 'workers_onsite', label: 'Workers' },
      { key: 'incidents_today', label: 'Incidents' },
      { key: 'status', label: 'Status', type: 'status' }
    ],
    detailFields: [
      { key: 'report_date', label: 'Report Date', type: 'date' },
      { key: 'site_name', label: 'Site Name' },
      { key: 'submitted_by', label: 'Submitted By' },
      { key: 'weather', label: 'Weather' },
      { key: 'temperature', label: 'Temperature' },
      { key: 'workers_onsite', label: 'Workers Onsite' },
      { key: 'incidents_today', label: 'Incidents Today' },
      { key: 'near_misses', label: 'Near Misses' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'toolbox_talk_topic', label: 'Toolbox Talk Topic', fullWidth: true },
      { key: 'work_summary', label: 'Work Summary', fullWidth: true },
      { key: 'safety_observations', label: 'Safety Observations', fullWidth: true },
      { key: 'visitors', label: 'Visitors', fullWidth: true },
      { key: 'equipment_issues', label: 'Equipment Issues', fullWidth: true }
    ],
    formFields: [
      { key: 'report_date', label: 'Report Date', type: 'date', required: true },
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'submitted_by', label: 'Submitted By', required: true },
      { key: 'weather', label: 'Weather' },
      { key: 'temperature', label: 'Temperature' },
      { key: 'workers_onsite', label: 'Workers Onsite', type: 'number' },
      { key: 'incidents_today', label: 'Incidents Today', type: 'number' },
      { key: 'near_misses', label: 'Near Misses', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['submitted', 'approved', 'rejected'] },
      { key: 'toolbox_talk_topic', label: 'Toolbox Talk Topic' },
      { key: 'work_summary', label: 'Work Summary', type: 'textarea', fullWidth: true, required: true },
      { key: 'safety_observations', label: 'Safety Observations', type: 'textarea', fullWidth: true },
      { key: 'visitors', label: 'Visitors', type: 'textarea', fullWidth: true },
      { key: 'equipment_issues', label: 'Equipment Issues', type: 'textarea', fullWidth: true }
    ]
  }
];
